// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

#![allow(
non_camel_case_types,
unused,
non_snake_case,
clippy::needless_return,
clippy::redundant_closure_call,
clippy::redundant_closure,
clippy::useless_conversion,
clippy::unit_arg,
clippy::unused_unit,
clippy::double_parens,
clippy::let_and_return,
clippy::too_many_arguments,
clippy::match_single_binding,
clippy::clone_on_copy,
clippy::let_unit_value,
clippy::deref_addrof,
clippy::explicit_auto_deref,
clippy::borrow_deref_ref,
clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
                    default_stream_sink_codec = DcoCodec,
                    default_rust_opaque = RustOpaqueMoi,
                    default_rust_auto_opaque = RustAutoOpaqueMoi,
                );
                pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.9.0";
                pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1585710994;
            

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__cancel_copy_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "cancel_copy", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok({ crate::api::cancel_copy(); })?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__compute_file_hash_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "compute_file_hash", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_file_path = <String>::sse_decode(&mut deserializer);
let api_algorithm = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::compute_file_hash(api_file_path, api_algorithm))?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__copy_files_batch_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "copy_files_batch", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_files = <Vec<crate::api::NativeFileEntry>>::sse_decode(&mut deserializer);
let api_max_threads = <u32>::sse_decode(&mut deserializer);
let api_skip_existing = <bool>::sse_decode(&mut deserializer);
let api_verify_integrity = <bool>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::copy_files_batch(api_files, api_max_threads, api_skip_existing, api_verify_integrity))?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__copy_single_file_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "copy_single_file", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_source = <String>::sse_decode(&mut deserializer);
let api_destination = <String>::sse_decode(&mut deserializer);
let api_skip_existing = <bool>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::copy_single_file(api_source, api_destination, api_skip_existing))?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__is_cancelled_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "is_cancelled", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::is_cancelled())?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__is_paused_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "is_paused", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::is_paused())?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__pause_copy_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "pause_copy", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok({ crate::api::pause_copy(); })?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__process_images_for_upload_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "process_images_for_upload", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_source_paths = <Vec<String>>::sse_decode(&mut deserializer);
let api_output_dir = <String>::sse_decode(&mut deserializer);
let api_thumb_width = <u32>::sse_decode(&mut deserializer);
let api_preview_width = <u32>::sse_decode(&mut deserializer);
let api_thumb_quality = <u8>::sse_decode(&mut deserializer);
let api_preview_quality = <u8>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::process_images_for_upload(api_source_paths, api_output_dir, api_thumb_width, api_preview_width, api_thumb_quality, api_preview_quality))?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__resume_copy_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "resume_copy", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok({ crate::api::resume_copy(); })?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__scan_directory_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "scan_directory", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
let api_extensions = <Vec<String>>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::scan_directory(api_path, api_extensions))?;   Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__verify_file_integrity_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "verify_file_integrity", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || { 
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_source = <String>::sse_decode(&mut deserializer);
let api_destination = <String>::sse_decode(&mut deserializer);
let api_algorithm = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Result::<_,()>::Ok(crate::api::verify_file_integrity(api_source, api_destination, api_algorithm))?;   Ok(output_ok)
                    })())
                } })
            }

// Section: dart2rust


                impl SseDecode for String {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();}
                }
                
                impl SseDecode for bool {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u8().unwrap() != 0}
                }
                
                impl SseDecode for f64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_f64::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for Vec<String> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ { ans_.push(<String>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for Vec<crate::api::NativeFileCopyResult> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ { ans_.push(<crate::api::NativeFileCopyResult>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for Vec<crate::api::NativeFileEntry> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ { ans_.push(<crate::api::NativeFileEntry>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for Vec<crate::api::NativeImageResult> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ { ans_.push(<crate::api::NativeImageResult>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for Vec<u8> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ { ans_.push(<u8>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for crate::api::NativeBatchResult {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_results = <Vec<crate::api::NativeFileCopyResult>>::sse_decode(deserializer);
let mut var_totalBytesCopied = <u64>::sse_decode(deserializer);
let mut var_totalFiles = <u32>::sse_decode(deserializer);
let mut var_successfulCount = <u32>::sse_decode(deserializer);
let mut var_failedCount = <u32>::sse_decode(deserializer);
let mut var_skippedCount = <u32>::sse_decode(deserializer);
let mut var_totalDurationMs = <u64>::sse_decode(deserializer);
let mut var_averageSpeedMbps = <f64>::sse_decode(deserializer);
let mut var_peakSpeedMbps = <f64>::sse_decode(deserializer);
let mut var_cancelled = <bool>::sse_decode(deserializer);
return crate::api::NativeBatchResult{results: var_results, total_bytes_copied: var_totalBytesCopied, total_files: var_totalFiles, successful_count: var_successfulCount, failed_count: var_failedCount, skipped_count: var_skippedCount, total_duration_ms: var_totalDurationMs, average_speed_mbps: var_averageSpeedMbps, peak_speed_mbps: var_peakSpeedMbps, cancelled: var_cancelled};}
                }
                
                impl SseDecode for crate::api::NativeFileCopyResult {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_sourcePath = <String>::sse_decode(deserializer);
let mut var_destPath = <String>::sse_decode(deserializer);
let mut var_bytesCopied = <u64>::sse_decode(deserializer);
let mut var_durationMs = <u64>::sse_decode(deserializer);
let mut var_speedMbps = <f64>::sse_decode(deserializer);
let mut var_strategyUsed = <String>::sse_decode(deserializer);
let mut var_success = <bool>::sse_decode(deserializer);
let mut var_errorMessage = <String>::sse_decode(deserializer);
let mut var_skipped = <bool>::sse_decode(deserializer);
return crate::api::NativeFileCopyResult{source_path: var_sourcePath, dest_path: var_destPath, bytes_copied: var_bytesCopied, duration_ms: var_durationMs, speed_mbps: var_speedMbps, strategy_used: var_strategyUsed, success: var_success, error_message: var_errorMessage, skipped: var_skipped};}
                }
                
                impl SseDecode for crate::api::NativeFileEntry {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_sourcePath = <String>::sse_decode(deserializer);
let mut var_destPath = <String>::sse_decode(deserializer);
let mut var_size = <u64>::sse_decode(deserializer);
return crate::api::NativeFileEntry{source_path: var_sourcePath, dest_path: var_destPath, size: var_size};}
                }
                
                impl SseDecode for crate::api::NativeHashResult {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_hash = <String>::sse_decode(deserializer);
let mut var_algorithm = <String>::sse_decode(deserializer);
let mut var_success = <bool>::sse_decode(deserializer);
let mut var_errorMessage = <String>::sse_decode(deserializer);
return crate::api::NativeHashResult{hash: var_hash, algorithm: var_algorithm, success: var_success, error_message: var_errorMessage};}
                }
                
                impl SseDecode for crate::api::NativeImageResult {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_sourcePath = <String>::sse_decode(deserializer);
let mut var_thumbPath = <String>::sse_decode(deserializer);
let mut var_previewPath = <String>::sse_decode(deserializer);
let mut var_thumbSize = <u64>::sse_decode(deserializer);
let mut var_previewSize = <u64>::sse_decode(deserializer);
let mut var_durationMs = <u64>::sse_decode(deserializer);
let mut var_success = <bool>::sse_decode(deserializer);
let mut var_errorMessage = <String>::sse_decode(deserializer);
return crate::api::NativeImageResult{source_path: var_sourcePath, thumb_path: var_thumbPath, preview_path: var_previewPath, thumb_size: var_thumbSize, preview_size: var_previewSize, duration_ms: var_durationMs, success: var_success, error_message: var_errorMessage};}
                }
                
                impl SseDecode for u32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u32::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for u64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u64::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for u8 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u8().unwrap()}
                }
                
                impl SseDecode for () {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
                }
                
                impl SseDecode for i32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_i32::<NativeEndian>().unwrap()}
                }
                
                fn pde_ffi_dispatcher_primary_impl(
                    func_id: i32,port: flutter_rust_bridge::for_generated::MessagePort,
                    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
                    rust_vec_len: i32,
                    data_len: i32,
                )  {
                    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
                    match func_id {
                        1 => wire__crate__api__cancel_copy_impl(port, ptr, rust_vec_len, data_len),
2 => wire__crate__api__compute_file_hash_impl(port, ptr, rust_vec_len, data_len),
3 => wire__crate__api__copy_files_batch_impl(port, ptr, rust_vec_len, data_len),
4 => wire__crate__api__copy_single_file_impl(port, ptr, rust_vec_len, data_len),
5 => wire__crate__api__is_cancelled_impl(port, ptr, rust_vec_len, data_len),
6 => wire__crate__api__is_paused_impl(port, ptr, rust_vec_len, data_len),
7 => wire__crate__api__pause_copy_impl(port, ptr, rust_vec_len, data_len),
8 => wire__crate__api__process_images_for_upload_impl(port, ptr, rust_vec_len, data_len),
9 => wire__crate__api__resume_copy_impl(port, ptr, rust_vec_len, data_len),
10 => wire__crate__api__scan_directory_impl(port, ptr, rust_vec_len, data_len),
11 => wire__crate__api__verify_file_integrity_impl(port, ptr, rust_vec_len, data_len),
                        _ => unreachable!(),
                    }
                }
                
                fn pde_ffi_dispatcher_sync_impl(
                    func_id: i32,
                    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
                    rust_vec_len: i32,
                    data_len: i32,
                ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
                    match func_id {
                        
                        _ => unreachable!(),
                    }
                }
                

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::NativeBatchResult {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.results.into_into_dart().into_dart(),
self.total_bytes_copied.into_into_dart().into_dart(),
self.total_files.into_into_dart().into_dart(),
self.successful_count.into_into_dart().into_dart(),
self.failed_count.into_into_dart().into_dart(),
self.skipped_count.into_into_dart().into_dart(),
self.total_duration_ms.into_into_dart().into_dart(),
self.average_speed_mbps.into_into_dart().into_dart(),
self.peak_speed_mbps.into_into_dart().into_dart(),
self.cancelled.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::NativeBatchResult {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::NativeBatchResult> for crate::api::NativeBatchResult {
            fn into_into_dart(self) -> crate::api::NativeBatchResult {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::NativeFileCopyResult {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.source_path.into_into_dart().into_dart(),
self.dest_path.into_into_dart().into_dart(),
self.bytes_copied.into_into_dart().into_dart(),
self.duration_ms.into_into_dart().into_dart(),
self.speed_mbps.into_into_dart().into_dart(),
self.strategy_used.into_into_dart().into_dart(),
self.success.into_into_dart().into_dart(),
self.error_message.into_into_dart().into_dart(),
self.skipped.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::NativeFileCopyResult {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::NativeFileCopyResult> for crate::api::NativeFileCopyResult {
            fn into_into_dart(self) -> crate::api::NativeFileCopyResult {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::NativeFileEntry {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.source_path.into_into_dart().into_dart(),
self.dest_path.into_into_dart().into_dart(),
self.size.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::NativeFileEntry {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::NativeFileEntry> for crate::api::NativeFileEntry {
            fn into_into_dart(self) -> crate::api::NativeFileEntry {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::NativeHashResult {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.hash.into_into_dart().into_dart(),
self.algorithm.into_into_dart().into_dart(),
self.success.into_into_dart().into_dart(),
self.error_message.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::NativeHashResult {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::NativeHashResult> for crate::api::NativeHashResult {
            fn into_into_dart(self) -> crate::api::NativeHashResult {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::NativeImageResult {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.source_path.into_into_dart().into_dart(),
self.thumb_path.into_into_dart().into_dart(),
self.preview_path.into_into_dart().into_dart(),
self.thumb_size.into_into_dart().into_dart(),
self.preview_size.into_into_dart().into_dart(),
self.duration_ms.into_into_dart().into_dart(),
self.success.into_into_dart().into_dart(),
self.error_message.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::NativeImageResult {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::NativeImageResult> for crate::api::NativeImageResult {
            fn into_into_dart(self) -> crate::api::NativeImageResult {
                self
            }
        }

                impl SseEncode for String {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<Vec<u8>>::sse_encode(self.into_bytes(), serializer);}
                }
                
                impl SseEncode for bool {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u8(self as _).unwrap();}
                }
                
                impl SseEncode for f64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_f64::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for Vec<String> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <String>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for Vec<crate::api::NativeFileCopyResult> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <crate::api::NativeFileCopyResult>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for Vec<crate::api::NativeFileEntry> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <crate::api::NativeFileEntry>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for Vec<crate::api::NativeImageResult> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <crate::api::NativeImageResult>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for Vec<u8> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <u8>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for crate::api::NativeBatchResult {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<Vec<crate::api::NativeFileCopyResult>>::sse_encode(self.results, serializer);
<u64>::sse_encode(self.total_bytes_copied, serializer);
<u32>::sse_encode(self.total_files, serializer);
<u32>::sse_encode(self.successful_count, serializer);
<u32>::sse_encode(self.failed_count, serializer);
<u32>::sse_encode(self.skipped_count, serializer);
<u64>::sse_encode(self.total_duration_ms, serializer);
<f64>::sse_encode(self.average_speed_mbps, serializer);
<f64>::sse_encode(self.peak_speed_mbps, serializer);
<bool>::sse_encode(self.cancelled, serializer);}
                }
                
                impl SseEncode for crate::api::NativeFileCopyResult {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.source_path, serializer);
<String>::sse_encode(self.dest_path, serializer);
<u64>::sse_encode(self.bytes_copied, serializer);
<u64>::sse_encode(self.duration_ms, serializer);
<f64>::sse_encode(self.speed_mbps, serializer);
<String>::sse_encode(self.strategy_used, serializer);
<bool>::sse_encode(self.success, serializer);
<String>::sse_encode(self.error_message, serializer);
<bool>::sse_encode(self.skipped, serializer);}
                }
                
                impl SseEncode for crate::api::NativeFileEntry {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.source_path, serializer);
<String>::sse_encode(self.dest_path, serializer);
<u64>::sse_encode(self.size, serializer);}
                }
                
                impl SseEncode for crate::api::NativeHashResult {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.hash, serializer);
<String>::sse_encode(self.algorithm, serializer);
<bool>::sse_encode(self.success, serializer);
<String>::sse_encode(self.error_message, serializer);}
                }
                
                impl SseEncode for crate::api::NativeImageResult {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.source_path, serializer);
<String>::sse_encode(self.thumb_path, serializer);
<String>::sse_encode(self.preview_path, serializer);
<u64>::sse_encode(self.thumb_size, serializer);
<u64>::sse_encode(self.preview_size, serializer);
<u64>::sse_encode(self.duration_ms, serializer);
<bool>::sse_encode(self.success, serializer);
<String>::sse_encode(self.error_message, serializer);}
                }
                
                impl SseEncode for u32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u32::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for u64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u64::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for u8 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u8(self).unwrap();}
                }
                
                impl SseEncode for () {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
                }
                
                impl SseEncode for i32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_i32::<NativeEndian>(self).unwrap();}
                }
                


        
        
        #[cfg(not(target_family = "wasm"))]
        mod io {
            // This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.



// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};use super::*;

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate_io!();


        }
        #[cfg(not(target_family = "wasm"))]
        pub use io::*;
        
        
        /// cbindgen:ignore
        #[cfg(target_family = "wasm")]
        mod web {
            // This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.



// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};use super::*;
                use flutter_rust_bridge::for_generated::wasm_bindgen;
                use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;


// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate_web!();


        }
        #[cfg(target_family = "wasm")]
        pub use web::*;
        