// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `NativeCopyProgress`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Copy a single file using the best strategy
Future<NativeFileCopyResult> copySingleFile({
  required String source,
  required String destination,
  required bool skipExisting,
}) => RustLib.instance.api.crateApiCopySingleFile(
  source: source,
  destination: destination,
  skipExisting: skipExisting,
);

/// Copy multiple files in parallel with progress reporting.
/// Returns batch result after all files are processed.
Future<NativeBatchResult> copyFilesBatch({
  required List<NativeFileEntry> files,
  required int maxThreads,
  required bool skipExisting,
  required bool verifyIntegrity,
}) => RustLib.instance.api.crateApiCopyFilesBatch(
  files: files,
  maxThreads: maxThreads,
  skipExisting: skipExisting,
  verifyIntegrity: verifyIntegrity,
);

/// Pause the current copy operation
Future<void> pauseCopy() => RustLib.instance.api.crateApiPauseCopy();

/// Resume the current copy operation
Future<void> resumeCopy() => RustLib.instance.api.crateApiResumeCopy();

/// Cancel the current copy operation
Future<void> cancelCopy() => RustLib.instance.api.crateApiCancelCopy();

/// Check if copy is currently paused
Future<bool> isPaused() => RustLib.instance.api.crateApiIsPaused();

/// Check if copy is cancelled
Future<bool> isCancelled() => RustLib.instance.api.crateApiIsCancelled();

/// Compute file hash (MD5 or SHA256)
Future<NativeHashResult> computeFileHash({
  required String filePath,
  required String algorithm,
}) => RustLib.instance.api.crateApiComputeFileHash(
  filePath: filePath,
  algorithm: algorithm,
);

/// Verify two files match by hash comparison
Future<bool> verifyFileIntegrity({
  required String source,
  required String destination,
  required String algorithm,
}) => RustLib.instance.api.crateApiVerifyFileIntegrity(
  source: source,
  destination: destination,
  algorithm: algorithm,
);

/// Scan directory and return list of files with their sizes
Future<List<NativeFileEntry>> scanDirectory({
  required String path,
  required List<String> extensions,
}) => RustLib.instance.api.crateApiScanDirectory(
  path: path,
  extensions: extensions,
);

/// Process images for web upload: generate thumbnail + preview WebP
Future<List<NativeImageResult>> processImagesForUpload({
  required List<String> sourcePaths,
  required String outputDir,
  required int thumbWidth,
  required int previewWidth,
  required int thumbQuality,
  required int previewQuality,
}) => RustLib.instance.api.crateApiProcessImagesForUpload(
  sourcePaths: sourcePaths,
  outputDir: outputDir,
  thumbWidth: thumbWidth,
  previewWidth: previewWidth,
  thumbQuality: thumbQuality,
  previewQuality: previewQuality,
);

/// Batch copy result — sent to Dart
class NativeBatchResult {
  final List<NativeFileCopyResult> results;
  final BigInt totalBytesCopied;
  final int totalFiles;
  final int successfulCount;
  final int failedCount;
  final int skippedCount;
  final BigInt totalDurationMs;
  final double averageSpeedMbps;
  final double peakSpeedMbps;
  final bool cancelled;

  const NativeBatchResult({
    required this.results,
    required this.totalBytesCopied,
    required this.totalFiles,
    required this.successfulCount,
    required this.failedCount,
    required this.skippedCount,
    required this.totalDurationMs,
    required this.averageSpeedMbps,
    required this.peakSpeedMbps,
    required this.cancelled,
  });

  @override
  int get hashCode =>
      results.hashCode ^
      totalBytesCopied.hashCode ^
      totalFiles.hashCode ^
      successfulCount.hashCode ^
      failedCount.hashCode ^
      skippedCount.hashCode ^
      totalDurationMs.hashCode ^
      averageSpeedMbps.hashCode ^
      peakSpeedMbps.hashCode ^
      cancelled.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeBatchResult &&
          runtimeType == other.runtimeType &&
          results == other.results &&
          totalBytesCopied == other.totalBytesCopied &&
          totalFiles == other.totalFiles &&
          successfulCount == other.successfulCount &&
          failedCount == other.failedCount &&
          skippedCount == other.skippedCount &&
          totalDurationMs == other.totalDurationMs &&
          averageSpeedMbps == other.averageSpeedMbps &&
          peakSpeedMbps == other.peakSpeedMbps &&
          cancelled == other.cancelled;
}

/// Single file copy result — sent to Dart
class NativeFileCopyResult {
  final String sourcePath;
  final String destPath;
  final BigInt bytesCopied;
  final BigInt durationMs;
  final double speedMbps;
  final String strategyUsed;
  final bool success;
  final String errorMessage;
  final bool skipped;

  const NativeFileCopyResult({
    required this.sourcePath,
    required this.destPath,
    required this.bytesCopied,
    required this.durationMs,
    required this.speedMbps,
    required this.strategyUsed,
    required this.success,
    required this.errorMessage,
    required this.skipped,
  });

  @override
  int get hashCode =>
      sourcePath.hashCode ^
      destPath.hashCode ^
      bytesCopied.hashCode ^
      durationMs.hashCode ^
      speedMbps.hashCode ^
      strategyUsed.hashCode ^
      success.hashCode ^
      errorMessage.hashCode ^
      skipped.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeFileCopyResult &&
          runtimeType == other.runtimeType &&
          sourcePath == other.sourcePath &&
          destPath == other.destPath &&
          bytesCopied == other.bytesCopied &&
          durationMs == other.durationMs &&
          speedMbps == other.speedMbps &&
          strategyUsed == other.strategyUsed &&
          success == other.success &&
          errorMessage == other.errorMessage &&
          skipped == other.skipped;
}

/// File entry for batch operations — received from Dart
class NativeFileEntry {
  final String sourcePath;
  final String destPath;
  final BigInt size;

  const NativeFileEntry({
    required this.sourcePath,
    required this.destPath,
    required this.size,
  });

  @override
  int get hashCode => sourcePath.hashCode ^ destPath.hashCode ^ size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeFileEntry &&
          runtimeType == other.runtimeType &&
          sourcePath == other.sourcePath &&
          destPath == other.destPath &&
          size == other.size;
}

/// Hash verification result
class NativeHashResult {
  final String hash;
  final String algorithm;
  final bool success;
  final String errorMessage;

  const NativeHashResult({
    required this.hash,
    required this.algorithm,
    required this.success,
    required this.errorMessage,
  });

  @override
  int get hashCode =>
      hash.hashCode ^
      algorithm.hashCode ^
      success.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeHashResult &&
          runtimeType == other.runtimeType &&
          hash == other.hash &&
          algorithm == other.algorithm &&
          success == other.success &&
          errorMessage == other.errorMessage;
}

/// Image processing result — sent to Dart
class NativeImageResult {
  final String sourcePath;
  final String thumbPath;
  final String previewPath;
  final BigInt thumbSize;
  final BigInt previewSize;
  final BigInt durationMs;
  final bool success;
  final String errorMessage;

  const NativeImageResult({
    required this.sourcePath,
    required this.thumbPath,
    required this.previewPath,
    required this.thumbSize,
    required this.previewSize,
    required this.durationMs,
    required this.success,
    required this.errorMessage,
  });

  @override
  int get hashCode =>
      sourcePath.hashCode ^
      thumbPath.hashCode ^
      previewPath.hashCode ^
      thumbSize.hashCode ^
      previewSize.hashCode ^
      durationMs.hashCode ^
      success.hashCode ^
      errorMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeImageResult &&
          runtimeType == other.runtimeType &&
          sourcePath == other.sourcePath &&
          thumbPath == other.thumbPath &&
          previewPath == other.previewPath &&
          thumbSize == other.thumbSize &&
          previewSize == other.previewSize &&
          durationMs == other.durationMs &&
          success == other.success &&
          errorMessage == other.errorMessage;
}
