// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1585710994;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'filecopy_native',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiCancelCopy();

  Future<NativeHashResult> crateApiComputeFileHash({
    required String filePath,
    required String algorithm,
  });

  Future<NativeBatchResult> crateApiCopyFilesBatch({
    required List<NativeFileEntry> files,
    required int maxThreads,
    required bool skipExisting,
    required bool verifyIntegrity,
  });

  Future<NativeFileCopyResult> crateApiCopySingleFile({
    required String source,
    required String destination,
    required bool skipExisting,
  });

  Future<bool> crateApiIsCancelled();

  Future<bool> crateApiIsPaused();

  Future<void> crateApiPauseCopy();

  Future<List<NativeImageResult>> crateApiProcessImagesForUpload({
    required List<String> sourcePaths,
    required String outputDir,
    required int thumbWidth,
    required int previewWidth,
    required int thumbQuality,
    required int previewQuality,
  });

  Future<void> crateApiResumeCopy();

  Future<List<NativeFileEntry>> crateApiScanDirectory({
    required String path,
    required List<String> extensions,
  });

  Future<bool> crateApiVerifyFileIntegrity({
    required String source,
    required String destination,
    required String algorithm,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiCancelCopy() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCancelCopyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCancelCopyConstMeta =>
      const TaskConstMeta(debugName: "cancel_copy", argNames: []);

  @override
  Future<NativeHashResult> crateApiComputeFileHash({
    required String filePath,
    required String algorithm,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          sse_encode_String(algorithm, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_native_hash_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiComputeFileHashConstMeta,
        argValues: [filePath, algorithm],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiComputeFileHashConstMeta => const TaskConstMeta(
    debugName: "compute_file_hash",
    argNames: ["filePath", "algorithm"],
  );

  @override
  Future<NativeBatchResult> crateApiCopyFilesBatch({
    required List<NativeFileEntry> files,
    required int maxThreads,
    required bool skipExisting,
    required bool verifyIntegrity,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_native_file_entry(files, serializer);
          sse_encode_u_32(maxThreads, serializer);
          sse_encode_bool(skipExisting, serializer);
          sse_encode_bool(verifyIntegrity, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_native_batch_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCopyFilesBatchConstMeta,
        argValues: [files, maxThreads, skipExisting, verifyIntegrity],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCopyFilesBatchConstMeta => const TaskConstMeta(
    debugName: "copy_files_batch",
    argNames: ["files", "maxThreads", "skipExisting", "verifyIntegrity"],
  );

  @override
  Future<NativeFileCopyResult> crateApiCopySingleFile({
    required String source,
    required String destination,
    required bool skipExisting,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(source, serializer);
          sse_encode_String(destination, serializer);
          sse_encode_bool(skipExisting, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_native_file_copy_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCopySingleFileConstMeta,
        argValues: [source, destination, skipExisting],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCopySingleFileConstMeta => const TaskConstMeta(
    debugName: "copy_single_file",
    argNames: ["source", "destination", "skipExisting"],
  );

  @override
  Future<bool> crateApiIsCancelled() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIsCancelledConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIsCancelledConstMeta =>
      const TaskConstMeta(debugName: "is_cancelled", argNames: []);

  @override
  Future<bool> crateApiIsPaused() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIsPausedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIsPausedConstMeta =>
      const TaskConstMeta(debugName: "is_paused", argNames: []);

  @override
  Future<void> crateApiPauseCopy() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPauseCopyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPauseCopyConstMeta =>
      const TaskConstMeta(debugName: "pause_copy", argNames: []);

  @override
  Future<List<NativeImageResult>> crateApiProcessImagesForUpload({
    required List<String> sourcePaths,
    required String outputDir,
    required int thumbWidth,
    required int previewWidth,
    required int thumbQuality,
    required int previewQuality,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_String(sourcePaths, serializer);
          sse_encode_String(outputDir, serializer);
          sse_encode_u_32(thumbWidth, serializer);
          sse_encode_u_32(previewWidth, serializer);
          sse_encode_u_8(thumbQuality, serializer);
          sse_encode_u_8(previewQuality, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_native_image_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProcessImagesForUploadConstMeta,
        argValues: [
          sourcePaths,
          outputDir,
          thumbWidth,
          previewWidth,
          thumbQuality,
          previewQuality,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProcessImagesForUploadConstMeta =>
      const TaskConstMeta(
        debugName: "process_images_for_upload",
        argNames: [
          "sourcePaths",
          "outputDir",
          "thumbWidth",
          "previewWidth",
          "thumbQuality",
          "previewQuality",
        ],
      );

  @override
  Future<void> crateApiResumeCopy() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiResumeCopyConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiResumeCopyConstMeta =>
      const TaskConstMeta(debugName: "resume_copy", argNames: []);

  @override
  Future<List<NativeFileEntry>> crateApiScanDirectory({
    required String path,
    required List<String> extensions,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_list_String(extensions, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_native_file_entry,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScanDirectoryConstMeta,
        argValues: [path, extensions],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScanDirectoryConstMeta => const TaskConstMeta(
    debugName: "scan_directory",
    argNames: ["path", "extensions"],
  );

  @override
  Future<bool> crateApiVerifyFileIntegrity({
    required String source,
    required String destination,
    required String algorithm,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(source, serializer);
          sse_encode_String(destination, serializer);
          sse_encode_String(algorithm, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiVerifyFileIntegrityConstMeta,
        argValues: [source, destination, algorithm],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiVerifyFileIntegrityConstMeta =>
      const TaskConstMeta(
        debugName: "verify_file_integrity",
        argNames: ["source", "destination", "algorithm"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<NativeFileCopyResult> dco_decode_list_native_file_copy_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_native_file_copy_result)
        .toList();
  }

  @protected
  List<NativeFileEntry> dco_decode_list_native_file_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_native_file_entry).toList();
  }

  @protected
  List<NativeImageResult> dco_decode_list_native_image_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_native_image_result).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  NativeBatchResult dco_decode_native_batch_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return NativeBatchResult(
      results: dco_decode_list_native_file_copy_result(arr[0]),
      totalBytesCopied: dco_decode_u_64(arr[1]),
      totalFiles: dco_decode_u_32(arr[2]),
      successfulCount: dco_decode_u_32(arr[3]),
      failedCount: dco_decode_u_32(arr[4]),
      skippedCount: dco_decode_u_32(arr[5]),
      totalDurationMs: dco_decode_u_64(arr[6]),
      averageSpeedMbps: dco_decode_f_64(arr[7]),
      peakSpeedMbps: dco_decode_f_64(arr[8]),
      cancelled: dco_decode_bool(arr[9]),
    );
  }

  @protected
  NativeFileCopyResult dco_decode_native_file_copy_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return NativeFileCopyResult(
      sourcePath: dco_decode_String(arr[0]),
      destPath: dco_decode_String(arr[1]),
      bytesCopied: dco_decode_u_64(arr[2]),
      durationMs: dco_decode_u_64(arr[3]),
      speedMbps: dco_decode_f_64(arr[4]),
      strategyUsed: dco_decode_String(arr[5]),
      success: dco_decode_bool(arr[6]),
      errorMessage: dco_decode_String(arr[7]),
      skipped: dco_decode_bool(arr[8]),
    );
  }

  @protected
  NativeFileEntry dco_decode_native_file_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return NativeFileEntry(
      sourcePath: dco_decode_String(arr[0]),
      destPath: dco_decode_String(arr[1]),
      size: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  NativeHashResult dco_decode_native_hash_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return NativeHashResult(
      hash: dco_decode_String(arr[0]),
      algorithm: dco_decode_String(arr[1]),
      success: dco_decode_bool(arr[2]),
      errorMessage: dco_decode_String(arr[3]),
    );
  }

  @protected
  NativeImageResult dco_decode_native_image_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return NativeImageResult(
      sourcePath: dco_decode_String(arr[0]),
      thumbPath: dco_decode_String(arr[1]),
      previewPath: dco_decode_String(arr[2]),
      thumbSize: dco_decode_u_64(arr[3]),
      previewSize: dco_decode_u_64(arr[4]),
      durationMs: dco_decode_u_64(arr[5]),
      success: dco_decode_bool(arr[6]),
      errorMessage: dco_decode_String(arr[7]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<NativeFileCopyResult> sse_decode_list_native_file_copy_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NativeFileCopyResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_native_file_copy_result(deserializer));
    }
    return ans_;
  }

  @protected
  List<NativeFileEntry> sse_decode_list_native_file_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NativeFileEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_native_file_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<NativeImageResult> sse_decode_list_native_image_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NativeImageResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_native_image_result(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  NativeBatchResult sse_decode_native_batch_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_results = sse_decode_list_native_file_copy_result(deserializer);
    var var_totalBytesCopied = sse_decode_u_64(deserializer);
    var var_totalFiles = sse_decode_u_32(deserializer);
    var var_successfulCount = sse_decode_u_32(deserializer);
    var var_failedCount = sse_decode_u_32(deserializer);
    var var_skippedCount = sse_decode_u_32(deserializer);
    var var_totalDurationMs = sse_decode_u_64(deserializer);
    var var_averageSpeedMbps = sse_decode_f_64(deserializer);
    var var_peakSpeedMbps = sse_decode_f_64(deserializer);
    var var_cancelled = sse_decode_bool(deserializer);
    return NativeBatchResult(
      results: var_results,
      totalBytesCopied: var_totalBytesCopied,
      totalFiles: var_totalFiles,
      successfulCount: var_successfulCount,
      failedCount: var_failedCount,
      skippedCount: var_skippedCount,
      totalDurationMs: var_totalDurationMs,
      averageSpeedMbps: var_averageSpeedMbps,
      peakSpeedMbps: var_peakSpeedMbps,
      cancelled: var_cancelled,
    );
  }

  @protected
  NativeFileCopyResult sse_decode_native_file_copy_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourcePath = sse_decode_String(deserializer);
    var var_destPath = sse_decode_String(deserializer);
    var var_bytesCopied = sse_decode_u_64(deserializer);
    var var_durationMs = sse_decode_u_64(deserializer);
    var var_speedMbps = sse_decode_f_64(deserializer);
    var var_strategyUsed = sse_decode_String(deserializer);
    var var_success = sse_decode_bool(deserializer);
    var var_errorMessage = sse_decode_String(deserializer);
    var var_skipped = sse_decode_bool(deserializer);
    return NativeFileCopyResult(
      sourcePath: var_sourcePath,
      destPath: var_destPath,
      bytesCopied: var_bytesCopied,
      durationMs: var_durationMs,
      speedMbps: var_speedMbps,
      strategyUsed: var_strategyUsed,
      success: var_success,
      errorMessage: var_errorMessage,
      skipped: var_skipped,
    );
  }

  @protected
  NativeFileEntry sse_decode_native_file_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourcePath = sse_decode_String(deserializer);
    var var_destPath = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    return NativeFileEntry(
      sourcePath: var_sourcePath,
      destPath: var_destPath,
      size: var_size,
    );
  }

  @protected
  NativeHashResult sse_decode_native_hash_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hash = sse_decode_String(deserializer);
    var var_algorithm = sse_decode_String(deserializer);
    var var_success = sse_decode_bool(deserializer);
    var var_errorMessage = sse_decode_String(deserializer);
    return NativeHashResult(
      hash: var_hash,
      algorithm: var_algorithm,
      success: var_success,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  NativeImageResult sse_decode_native_image_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourcePath = sse_decode_String(deserializer);
    var var_thumbPath = sse_decode_String(deserializer);
    var var_previewPath = sse_decode_String(deserializer);
    var var_thumbSize = sse_decode_u_64(deserializer);
    var var_previewSize = sse_decode_u_64(deserializer);
    var var_durationMs = sse_decode_u_64(deserializer);
    var var_success = sse_decode_bool(deserializer);
    var var_errorMessage = sse_decode_String(deserializer);
    return NativeImageResult(
      sourcePath: var_sourcePath,
      thumbPath: var_thumbPath,
      previewPath: var_previewPath,
      thumbSize: var_thumbSize,
      previewSize: var_previewSize,
      durationMs: var_durationMs,
      success: var_success,
      errorMessage: var_errorMessage,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_native_file_copy_result(
    List<NativeFileCopyResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_native_file_copy_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_native_file_entry(
    List<NativeFileEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_native_file_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_native_image_result(
    List<NativeImageResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_native_image_result(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_native_batch_result(
    NativeBatchResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_native_file_copy_result(self.results, serializer);
    sse_encode_u_64(self.totalBytesCopied, serializer);
    sse_encode_u_32(self.totalFiles, serializer);
    sse_encode_u_32(self.successfulCount, serializer);
    sse_encode_u_32(self.failedCount, serializer);
    sse_encode_u_32(self.skippedCount, serializer);
    sse_encode_u_64(self.totalDurationMs, serializer);
    sse_encode_f_64(self.averageSpeedMbps, serializer);
    sse_encode_f_64(self.peakSpeedMbps, serializer);
    sse_encode_bool(self.cancelled, serializer);
  }

  @protected
  void sse_encode_native_file_copy_result(
    NativeFileCopyResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sourcePath, serializer);
    sse_encode_String(self.destPath, serializer);
    sse_encode_u_64(self.bytesCopied, serializer);
    sse_encode_u_64(self.durationMs, serializer);
    sse_encode_f_64(self.speedMbps, serializer);
    sse_encode_String(self.strategyUsed, serializer);
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.errorMessage, serializer);
    sse_encode_bool(self.skipped, serializer);
  }

  @protected
  void sse_encode_native_file_entry(
    NativeFileEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sourcePath, serializer);
    sse_encode_String(self.destPath, serializer);
    sse_encode_u_64(self.size, serializer);
  }

  @protected
  void sse_encode_native_hash_result(
    NativeHashResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.hash, serializer);
    sse_encode_String(self.algorithm, serializer);
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_native_image_result(
    NativeImageResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sourcePath, serializer);
    sse_encode_String(self.thumbPath, serializer);
    sse_encode_String(self.previewPath, serializer);
    sse_encode_u_64(self.thumbSize, serializer);
    sse_encode_u_64(self.previewSize, serializer);
    sse_encode_u_64(self.durationMs, serializer);
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
